# Production docker-compose File
version: "3.7"
services:
  db:
    image: mariadb:10.9
    container_name: lolapi-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - lol-api
  app:
    image: ghcr.io/phinocio/loadorderlibrary-api:testing
    container_name: lolapi-prod
    restart: unless-stopped
    entrypoint: sh -c "php artisan config:cache && php artisan route:cache && php artisan migrate && exec php-fpm"
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_KEY: ${APP_KEY}
      APP_URL: ${APP_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      SESSION_DOMAIN: ${SESSION_DOMAIN}
      LOCAL_DOMAINS: ${LOCAL_DOMAINS}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./storage/:/var/www/storage/
    networks:
      - lol-api
    depends_on: [db]
  nginx:
    image: nginx:1.25.0-alpine
    container_name: lolapi-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/public
      - ./docker/prod/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/prod/nginx/sites-enabled:/etc/nginx/sites-enabled
      - /var/log/nginx/lolapi-dev:/var/log/nginx
    networks:
      - lol-api
    depends_on: [app]

networks:
  lol-api:
    driver: bridge

volumes:
  mariadb_data:
