# Testing docker-compose File
version: "3.7"
services:
  db:
    image: mariadb:10.9
    container_name: lolapi-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - lol-api
  app:
    image: ghcr.io/phinocio/loadorderlibrary-api:testing
    container_name: lolapi-testing
    restart: unless-stopped
    entrypoint: sh -c "php artisan config:cache && php artisan route:cache && php artisan migrate:fresh --seed && exec php-fpm"
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_KEY: ${APP_KEY}
      APP_URL: ${APP_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      SESSION_DOMAIN: ${SESSION_DOMAIN}
      LOCAL_DOMAINS: ${LOCAL_DOMAINS}git
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./storage/:/var/www/storage/
    networks:
      - lol-api
    depends_on: [db]
  nginx:
    image: nginx:1.25.0-alpine
    container_name: lolapi-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      # - "8000:80"
    volumes:
      - ./public:/var/www/public
      - ./docker/testing/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /var/log/nginx/lolapi-dev:/var/log/nginx
      - certbot_etc:/etc/letsencrypt
      - certbot_var:/var/lib/letsencrypt
      - le_challenge:/var/www/_letsencrypt
      - ./docker/testing/nginx/dhparam:/etc/nginx/dhparam
    networks:
      - lol-api
    depends_on: [app]
  certbot:
    image: certbot/certbot
    container_name: certbot-api
    volumes:
      - certbot_etc:/etc/letsencrypt
      - certbot_var:/var/lib/letsencrypt
      - le_challenge:/var/www/_letsencrypt
    depends_on: [nginx]
    command: certonly --webroot -d dockertest2.loadorderlibrary.com --email letsencrypt@loadorderlibrary.com -w /var/www/_letsencrypt -n --agree-tos --force-renewal --no-eff-email --dry-run

networks:
  lol-api:
    driver: bridge

volumes:
  mariadb_data:
  certbot_etc:
  certbot_var:
  le_challenge:
