# Docker compose file for testing environment

services:
  db:
    image: mariadb:10.9
    container_name: lol-testing-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_NAME: mariadb
    profiles: ["testing", "local"]
    volumes:
      - lol-testing-db:/var/lib/mysql
    networks:
      - lol-db
  app:
    image: ghcr.io/phinocio/loadorderlibrary-api:testing
    container_name: lol-testingapi-app
    restart: unless-stopped
    entrypoint: sh -c "php artisan config:cache && php artisan route:cache && php artisan migrate:fresh --seed && exec php-fpm"
    env_file: .env
    user: "2000:2000"
    profiles: ["testing", "local"]
    volumes:
      - ./storage/:/var/www/storage/
    networks:
      - lol
      - lol-db
    depends_on: [lol-testing-db]
  nginx:
    image: nginx:1.25.0-alpine
    container_name: lol-testingapi-nginx
    restart: unless-stopped
    profiles: ["local"]
    volumes:
      - ./public:/var/www/public
      - ./docker/testing/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/testing/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - /var/log/nginx/lolapi-testing:/var/log/nginx
    networks:
      - lol
    depends_on: [app]

networks:
  lol:
    external: true
  lol-db:
    external: true

volumes:
  lol-testingapi-db:
