# Docker compose file for testing environment

services:
  db:
    image: mariadb:10.9
    container_name: lol-testing-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_NAME: mariadb
    volumes:
      - lol-testing-db:/var/lib/mysql
    networks:
      - lol-db
  app:
    image: ghcr.io/phinocio/loadorderlibrary-api:testing
    container_name: lol-testingapi-app
    restart: unless-stopped
    entrypoint: sh -c "php artisan config:cache && php artisan route:cache && php artisan migrate:fresh --seed && exec php-fpm"
    env_file: .env
    user: "2000:2000"
    ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - ./storage:/srv/testingapi.loadorderlibrary.com/storage
    networks:
      - lol
      - lol-db
    depends_on: [db]

networks:
  lol:
    external: true
  lol-db:
    external: true

volumes:
  lol-testing-db:
