# Local Development docker-compose File.
version: "3.7"
services:
    db:
        image: mariadb:10.9
        container_name: lolapi-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mariadb
        volumes:
            - mariadb_data:/var/lib/mysql
        networks:
            - lol-api
    app:
        build:
            context: .
            args:
                uid: 1000
            dockerfile: Dockerfile
            target: dev
        image: loadorderlibrary-api:dev
        container_name: lolapi-dev
        restart: unless-stopped
        volumes:
            - ./:/var/www
        networks:
            - lol-api
        depends_on: [db]
    nginx:
        image: nginx:1.25.0-alpine
        container_name: lolapi-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./public:/var/www/public
            - ./docker/dev/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/dev/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - /var/log/nginx/:/var/log/nginx
        networks:
            - lol-api
        depends_on: [app]
    promtail:
        image: grafana/promtail:2.8.2
        volumes:
            - /var/log/nginx:/var/log/nginx
            - ./promtail:/etc/promtail
        # ports:
        #   - "1514:1514" # this is only needed if you are going to send syslogs
        restart: unless-stopped
        command: -config.file=/etc/promtail/promtail-config.yml
        networks:
            - lol-api

networks:
    lol-api:
        driver: bridge

volumes:
    mariadb_data:
