# Local Development docker compose file.
version: "3.7"
services:
  app:
    build:
      args:
        user: lol-api
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: loadorderlibrary-api
    restart: unless-stopped
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_KEY: ${APP_KEY}
      APP_URL: ${APP_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      SESSION_DOMAIN: ${SESSION_DOMAIN}
      LOCAL_DOMAINS: ${LOCAL_DOMAINS}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      PHP_OPCACHE_MEMORY_CONSUMPTION: ${PHP_OPCACHE_MEMORY_CONSUMPTION}
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: ${PHP_OPCACHE_VALIDATE_TIMESTAMPS}
      PHP_OPCACHE_MAX_ACCELERATED_FILES: ${PHP_OPCACHE_MAX_ACCELERATED_FILES}

    networks:
      - lol-api
    depends_on: [db]

  db:
    image: mariadb:10.6.13
    container_name: lol-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - lol-api

  nginx:
    image: nginx:1.25.0-alpine
    container_name: lol-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled
    networks:
      - lol-api

networks:
  lol-api:
    driver: bridge

volumes:
  mariadb_data:
