# Docker compose file for development environment (Proxmox)

services:
  db:
    image: mariadb:10.9
    container_name: lol-dev-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_NAME: mariadb
    volumes:
      - lol-dev-db:/var/lib/mysql
    networks:
      - lol-db
  app:
    image: ghcr.io/phinocio/loadorderlibrary-api:testing
    container_name: lol-devapi-app
    restart: unless-stopped
    entrypoint: sh -c "php artisan config:cache && php artisan route:cache && php artisan migrate:fresh --seed && exec php-fpm"
    env_file: .env
    user: "2000:2000"
    volumes:
      - ./storage/:/var/www/storage/
    networks:
      - lol
      - lol-db
    depends_on: [db]
  nginx:
    image: nginx:1.25.0-alpine
    container_name: lol-devapi-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/public
      - ./docker/dev/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/dev/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - /var/log/nginx/lolapi-dev:/var/log/nginx
    networks:
      - lol
    depends_on: [app]

networks:
  lol:
    external: true
  lol-db:
    external: true

volumes:
  lol-dev-db:
