# Local Development docker-compose File.
version: "3.7"
services:
    db:
        image: mariadb:10.9
        container_name: lolapi-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mariadb
        volumes:
            - mariadb_data:/var/lib/mysql
        networks:
            - lol-api
    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: dev
        image: loadorderlibrary-api:dev
        container_name: lolapi-dev
        restart: unless-stopped
        volumes:
            - ./:/var/www
        networks:
            - lol-api
        depends_on: [db]
    nginx:
        image: nginx:1.25.0-alpine
        container_name: lolapi-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./public:/var/www/public
            - ./docker/dev/nginx/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - lol-api
        depends_on: [app]

networks:
    lol-api:
        driver: bridge

volumes:
    mariadb_data:
