# Testing docker-compose File
version: "3.7"
services:
  db:
    image: mariadb:10.9
    container_name: lolapi-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_NAME: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - lol-api
  app:
    image: ghcr.io/phinocio/loadorderlibrary-api:testing
    container_name: lolapi-testing
    restart: unless-stopped
    entrypoint: sh -c "php artisan config:cache && php artisan route:cache && php artisan migrate:fresh --seed && exec php-fpm"
    env_file: .env
    user: "2000:2000"
    volumes:
      - ./storage/:/var/www/storage/
    networks:
      - lol-api
    depends_on: [db]
  nginx:
    image: nginx:1.25.0-alpine
    container_name: lolapi-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/public
      - ./docker/testing/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/testing/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - /var/log/nginx/lolapi-dev:/var/log/nginx
    networks:
      - lol-api
    depends_on: [app]

networks:
  lol-api:
    driver: bridge

volumes:
  mariadb_data:
  certbot_etc:
  certbot_var:
  le_challenge:
