# Local Development docker-compose File.
services:
  db:
    image: mariadb:10.9
    container_name: lol-dev-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mariadb
    volumes:
      - lol-dev-db:/var/lib/mysql
    networks:
      - lol-db
  app:
    build:
      context: .
      args:
        uid: 1000
        gid: 2010
      dockerfile: docker/dev/app/Dockerfile
      target: dev
    image: loadorderlibrary-api:dev
    entrypoint: sh -c "php artisan migrate:fresh --seed && exec php-fpm"
    container_name: lol-devapi-app
    restart: unless-stopped
    volumes:
      - ./:/srv/dev.loadorderlibrary.com
    networks:
      - lol
      - lol-db
    depends_on: [db]
  nginx:
    image: nginx:1.25.0-alpine
    container_name: lol-devapi-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./public:/srv/dev.loadorderlibrary.com/public
      - ./docker/dev/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/dev/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/dev/nginx/log:/var/log/nginx
    networks:
      - lol
    depends_on: [app]

networks:
  lol:
    name: lol
    external: true
  lol-db:
    name: lol-db
    external: true

volumes:
  lol-dev-db:
