server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/log/positions.yaml # This location needs to be writeable by Promtail.

clients:
  - url: http://10.0.120.10:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    pipeline_stages:
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx # A `job` label is fairly standard in prometheus and useful for linking metrics and logs.
          host: lolapi # A `host` label will help identify logs from this machine vs others
          __path__: /var/log/nginx/*.log # The path matching uses a third party library: https://github.com/bmatcuk/doublestar
