name: Create Testing Container

env:
  TAG: loadorderlibrary-api

on:
  push:
    branches: [testing]

jobs:
  build:
    name: Build Testing Container
    runs-on: ubuntu-latest
    env:
      USER: ${{ github.repository_owner }}
      REGISTRY: ghcr.io
      VERSION: testing
    steps:
      - uses: actions/checkout@v2

      - name: Build Container Image
        # We target prod because testing and prod have the same considerations, just different code in the image.
        run: docker build --target prod -t $TAG .

      - name: Push to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
          docker tag $TAG ${{ env.REGISTRY }}/$USER/$TAG:${{ env.VERSION }}
          docker push ${{ env.REGISTRY }}/$USER/$TAG:${{ env.VERSION }}
  deploy:
    name: Deploy Container to Server
    runs-on: ubuntu-latest
    needs: build
    steps:
      echo "${{ secrets.KEY }}" > ~/.ssh/id_ed25519
      ssh -i ~/.ssh/id_ed25519 "${{ secrets.USERNAME }}"@"${{ secrets.HOST }}"
      sudo /home/lolapi/loadorderlibrary-api/test.sh
