name: Create Testing Container

env:
  TAG: loadorderlibrary-api
  
on:
  push:
    branches: [ testing ]

jobs:
  build:
    name: Build Testing Container
    runs-on: ubuntu-latest
    env:
      USER: ${{ github.repository_owner }}
      REGISTRY: ghcr.io
      VERSION: testing
    steps:
      - uses: actions/checkout@v2
      
      - name: Build Container Image
        run: docker build --target prod -t $TAG .
      
      - name: Push to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
          docker tag $TAG $REGISTRY/$USER/$TAG:$VERSION
          docker push $REGISTER/$USER/$TAG:$VERSION
