name: Create Testing Container

env:
  TAG: loadorderlibrary-api

on:
  push:
    branches: [testing]

jobs:
  build:
    name: Build Testing Container
    runs-on: ubuntu-latest
    env:
      USER: ${{ github.repository_owner }}
      REGISTRY: ghcr.io
      VERSION: testing
    steps:
      - uses: actions/checkout@v2

      - name: Build Container Image
        run: docker build --target prod -t $TAG .

      - name: Push to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
          docker tag $TAG ${{ env.REGISTRY }}/$USER/$TAG:${{ env.VERSION }}
          docker push ${{ env.REGISTRY }}/$USER/$TAG:${{ env.VERSION }}
  deploy:
    name: Deploy Container to Server
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/lolapi/loadorderlibrary-api
            git checkout -f testing
            git pull
            docker compose pull app
            docker compose -f docker-compose.testing.yml up -d
            docker image prune -f
