name: Create Production Container

env:
  TAG: loadorderlibrary-api

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Production Container
    runs-on: ubuntu-latest
    env:
      USER: ${{ github.repository_owner }}
      REGISTRY: ghcr.io
      VERSION: latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Container Image
        run: docker build --target prod -t $TAG .

      - name: Push to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
          docker tag $TAG ${{ env.REGISTRY }}/$USER/$TAG:${{ env.VERSION }}
          docker push ${{ env.REGISTRY }}/$USER/$TAG:${{ env.VERSION }}
  deploy:
    name: Deploy Container to Server
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH and deploy
        run: |
          echo "${{ secrets.PROD_KEY }}" > id_meow
          chmod 600 id_meow
          ssh -p ${{ secrets.PROD_PORT }} -i id_meow "${{ secrets.PROD_USER }}"@"${{ secrets.PROD_HOST }}" -o "StrictHostKeyChecking no" "sudo ${{ secrets.PROD_DEPLOY }}"
